# Nothing configurable here, use bird.local.conf

log syslog all;

router id ROUTER_ID;

protocol device {
    ipv4;
    ipv6;
}

protocol kernel connected_ipv4 {
    ipv4;
    import where net.len == 32 && source = RTS_DEVICE;
    export none;
    scan time 10;
}

protocol kernel v6_net {
    ipv6;
    import all;
    export none;
    scan time 10;
}

# Static constants
define BASE_ASN = 4200100000;
define LOCAL_ASN = BASE_ASN + ASN_OFFSET;

define PEER_ADDR = fd00:614::;
define PEER_ASN = 4200000000;

protocol bgp upstream {
    local as LOCAL_ASN;
    neighbor PEER_ADDR as PEER_ASN;
    multihop 2;
    password BGP_PASSWORD;
    graceful restart on;
    ipv4 {
        extended next hop on;

        export filter {
            if net.len = 32 && source = RTS_DEVICE then {
                set bgp_next_hop = self;
                accept;
            }
            reject;
        };
        import none;
    };
    
    local as MY_AS;
    neighbor fd00:614:: as 65001;

    ipv4 {
        extended next hop on;
        import none;
        export filter {
            if net.len = 32 && source = RTS_DEVICE then {
                bgp_next_hop = MY_IPV6;
                accept;
            }
            reject;
        };
    };

    ipv6 {
        import none;
        export none;
    };