log syslog all;

# debug protocols all;
# debug protocols { events, states };

# You can define your own constants
define MY_AS = 4200000000;
define MY_IP = 192.168.254.254;
define MY_IPV6 = fd00:614::;

router id MY_IP;

protocol device {}

protocol static static_includes {
    ipv4;
    include "/etc/bird/includes/static/*.conf"
}

protocol static static_includes_v6 {
    ipv6;
    route fd00:614::/128 via "lo";
}

template bgp injector_routers {
    local as MY_AS;
    neighbor as MY_AS;
    ipv4 {
        extended next hop on;
        import none;
        export filter {
            bgp_next_hop = gw;
            accept;
        };
    };
    ipv6 {
        next hop self;
        import none;
        export where net.len = 128;
    };
}

template bgp injector_clients {
    hosts = [];
    local fd00:614:: as 4200000000;
    passive;
    ipv4 {
        extended next hop on;
        export none;
        import where net ~ hosts;
    };
    ipv6 {};
}

include "/etc/bird/routers/*.conf";

include "/etc/bird/clients/*.conf";
