define myas = 65001;
define v4gw_host = [ 0.0.0.0/0{32,32} ];

router id 10.0.0.2;              # PER-NODE: gw2 10.0.0.2, gw3 10.0.0.3

log syslog all;

ipv6 table v6;

protocol device { scan time 10; }
protocol direct { ipv6 { table v6; import all; }; }

protocol kernel {
    learn;
    ipv4 { import all; export where source = RTS_BGP; };
}

template bgp v4gw_peers {
    local as myas;
    neighbor as myas;
    ipv4 {
        import where net ~ v4gw_host;
        export where net ~ v4gw_host && source = RTS_INHERIT;
        extended next hop on;
        igp table v6;
    };
}

protocol bgp gw_peer1 from v4gw_peers {
    local    2a06:2602:7c:8002::2;    # PER-NODE: this node's enp0s1 GUA
    neighbor 2a06:2602:7c:8002::3;    # PER-NODE: peer node's enp0s1 GUA
}
